#!/usr/bin/env bash
# Post the round-by-round Claude<->Codex exchange as a PR comment.
set -euo pipefail
RUN="${1:?run dir}"; PR="${2:-}"
[ -n "$PR" ] || { echo "[cx] no PR; skipping summary"; exit 0; }
MD="$RUN/exchange-summary.md"
{
  echo "## cx loop — Claude×Codex exchange summary"; echo
  for r in "$RUN"/review-round-*.json; do
    [ -f "$r" ] || continue
    n="$(basename "$r" | tr -dc '0-9')"
    python3 - "$r" "$n" <<'PY'
import json, sys
d = json.load(open(sys.argv[1])); n = sys.argv[2]
print(f"### Round {n} — Claude verdict: **{d.get('verdict','?')}**")
s = (d.get("summary") or "").strip()
if s: print(f"> {s}")
for f in d.get("findings", []):
    flag = "🚫 blocking" if f.get("blocking") else "note"
    print(f"- [{flag}] **{f.get('title','')}** ({f.get('severity','')}) `{f.get('file','')}`")
print()
PY
  done
  echo "_Generated by the cx loop (codex-skills/implement-plan)._"
} > "$MD"
gh pr comment "$PR" --body-file "$MD"
echo "[cx] summary posted to $PR"
